# Generated by Django 5.1.4 on 2025-01-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pushuplog", "0006_pushuplogentry_repetitions_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pushuplogentry",
            name="repetitions_total",
        ),
        migrations.RemoveField(
            model_name="pushuplogentry",
            name="sets",
        ),
    ]
