# Generated by Django 5.1.4 on 2025-02-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pushuplog", "0007_remove_pushuplogentry_repetitions_total_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pushuplogentry",
            options={"verbose_name_plural": "pushup log entries"},
        ),
    ]
